name: CICD Backend Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install ruff

      - name: Run tests with Pytest
        run: |
          pytest tests/

      - name: Run Lint with Ruff
        run: |
          ruff tarea_daw/backend

  build_and_push_dockerhub_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
           docker build -t ${{ vars.DOCKER_USERNAME }}/backend:latest tarea_daw/backend

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/backend:latest

  build_and_push_github_actions_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image for GitHub Actions
        run: |
          docker build -t ghcr.io/${GITHUB_REPOSITORY}/backend:latest tarea_daw/backend

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY}/backend:latest
